### ISSUE TITLE
Fails trying to find git

### ISSUE THREAD

**Issue by scarolan** [adamedx/winbox#1]
This commit seems to work, latest master does not.  Error output below.
https://github.com/adamedx/winbox/commit/238140c42da456bc8545cb39fab04fa433495b49

-----> Starting Kitchen (v1.4.0.rc.1)
-----> Creating <default-win2012r2>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'win2012r2'...
==> default: Matching MAC address for NAT networking...
       ==> default: Setting the name of the VM: kitchen-winbox-default-win2012r2_default_1433455211395_13513
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 3389 => 3389 (adapter 1)
           default: 5985 => 5985 (adapter 1)
           default: 22 => 2222 (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
       ==> default: Machine booted and ready!
       Sorry, don't know how to check guest version of Virtualbox Guest Additions on this platform. Stopping installation.
       ==> default: Checking for guest additions in VM...
       ==> default: Machine not provisioning because `--no-provision` is specified.
       [WinRM] Established
       Vagrant instance <default-win2012r2> created.
       Finished creating <default-win2012r2> (1m50.04s).
-----> Converging <default-win2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading package from https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-client-12.3.0-1.msi
       Download complete.
       Successfully verified C:\Users\vagrant\AppData\Local\Temp\chef-true.msi

```
   Installing Chef Omnibus package C:\Users\vagrant\AppData\Local\Temp\chef-true.msi
   Installation complete
   Transferring files to <default-win2012r2>
   Starting Chef Client, version 12.3.0
   Creating a new client identity for default-win2012r2 using the validator key.
   [2015-06-04T15:03:44-07:00] WARN: Child with name 'dna.json' found in multiple directories: C:/Users/vagrant/AppData/Local/Temp/kitchen/dna.json and C:/Users/vagrant/AppData/Local/Temp/kitchen/dna.json
   [2015-06-04T15:03:44-07:00] WARN: Child with name 'dna.json' found in multiple directories: C:/Users/vagrant/AppData/Local/Temp/kitchen/dna.json and C:/Users/vagrant/AppData/Local/Temp/kitchen/dna.json
   resolving cookbooks for run list: ["winbox::default", "winbox::desktop"]
   [2015-06-04T15:03:44-07:00] WARN: Child with name 'dna.json' found in multiple directories: C:/Users/vagrant/AppData/Local/Temp/kitchen/dna.json and C:/Users/vagrant/AppData/Local/Temp/kitchen/dna.json
   Synchronizing Cookbooks:
     - winbox
     - git
     - windows
     - build-essential
     - dmg
     - yum-epel
     - chef_handler
     - yum
   Compiling Cookbooks...

   ================================================================================
   Recipe Compile Error in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/winbox/recipes/default.rb
   ================================================================================

   ArgumentError
   -------------
   You must supply a name when declaring a windows_path resource

   Cookbook Trace:
   ---------------
     C:/opscode/chef/embedded/apps/chef/lib/chef/resource_builder.rb:46:in `build'
     C:/opscode/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:144:in `build_resource'
     C:/opscode/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:105:in `declare_resource'
     C:/opscode/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:44:in `method_missing'
     C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/winbox/recipes/default.rb:43:in `from_file'
     C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
     C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
     C:/opscode/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
     C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
     C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
     C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
     C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
     C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
     C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:96:in `load'
     C:/opscode/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
     C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:256:in `setup_run_context'
     C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:454:in `run'
     C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
     C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
     C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
     C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
     C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
     C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
     C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
     C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
     C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
     C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
     C:/opscode/chef/bin/chef-client:63:in `load'
     C:/opscode/chef/bin/chef-client:63:in `<main>'

   Relevant File Content:
   ----------------------
   C:/opscode/chef/embedded/apps/chef/lib/chef/resource_builder.rb:

    39:        @run_context        = run_context
    40:        @cookbook_name      = cookbook_name
    41:        @recipe_name        = recipe_name
    42:        @enclosing_provider = enclosing_provider
    43:      end
    44:
    45:      def build(&block)
    46>>       raise ArgumentError, "You must supply a name when declaring a #{type} resource" if name.nil?
    47:
    48:        @resource = resource_class.new(name, run_context)
    49:        resource.source_line = created_at
    50:        resource.declared_type = type
    51:
    52:        # If we have a resource like this one, we want to steal its state
    53:        # This behavior is very counter-intuitive and should be removed.
    54:        # See CHEF-3694, https://tickets.opscode.com/browse/CHEF-3694
    55:        # Moved to this location to resolve CHEF-5052, https://tickets.opscode.com/browse/CHEF-5052


   Running handlers:
   [2015-06-04T15:03:55-07:00] ERROR: Running exception handlers
   Running handlers complete
   [2015-06-04T15:03:55-07:00] ERROR: Exception handlers complete
   [2015-06-04T15:03:55-07:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
   Chef Client failed. 0 resources updated in 27.861491 seconds
   [2015-06-04T15:03:55-07:00] FATAL: ArgumentError: You must supply a name when declaring a windows_path resource
```

$$$$$$ get-command : The term 'git' is not recognized as the name of a cmdlet,
$$$$$$ function, script file, or operable program. Check the spelling of the name, or
$$$$$$ if a path was included, verify that the path is correct and try again.
$$$$$$ At line:1 char:2
$$$$$$ + (get-command git | select-object -property path).path
$$$$$$ +  ~~~~~~~~~~~~~~~
$$$$$$     + CategoryInfo          : ObjectNotFound: (git:String) [Get-Command], Comm
$$$$$$    andNotFoundException
$$$$$$     + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Co
$$$$$$    mmands.GetCommandCommand
$$$$$$

> > > > > > Converge failed on instance <default-win2012r2>.
> > > > > > Please see .kitchen/logs/default-win2012r2.log for more details
> > > > > > ------Exception-------
> > > > > > Class: Kitchen::ActionFailed
> > > > > > Message: WinRM exited (1) for command: [
> > > > > > $env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine")

& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level auto --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889]

**Comment by adamedx** [comment]
Thanks for submitting this @scarolan -- I actually merged the fix once you let me know a while ago, so closing it now, it should be working.
