### ISSUE TITLE
Windows 10: Fails on first run due to Internet Explorer engine not being available

### ISSUE THREAD

**Issue by chefsalim** [adamedx/winbox#5]
Steps:
1. Clean Win10 setup
2. Run Powershell as admin
3. Copy-paste the setup line

Result:
PS C:\Windows\system32> . { iwr https://raw.githubusercontent.com/adamedx/winbox/0.1.78/files/default/install.ps1 } | ie
x;install-workstation
iwr : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet
Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At line:1 char:5
- . { iwr https://raw.githubusercontent.com/adamedx/winbox/0.1.78/files ...
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
  - FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestComman
    d

Expected: No failure

**Comment by RickWilcox** [comment]
If you don't want to use basic parsing you can pass this command to write a registry key that should fix the error. 

New-ItemProperty -Path 'hklm:\SOFTWARE\Microsoft\Internet Explorer\Main\' -name 'DisableFirstRunCustomize' -PropertyType dword -Value 2 

Cheers!
